# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blopeur Ltd. Intellectual property Consulting Services
tagline: Bespoke Intellectual Property consulting solutions
email: info@blopeur.com
description: >
  Blopeur Ltd. is an Intellectual Property boutique consulting firm. We bring together patent expertise,
  technical excellence, and business acumen across a wide range of ICT markets and ICT technologies.
  We form strong partnerships with our clients, empowering them to grow their businesses, protect and profit from
  their intellectual property assets, and strategically position themselves for the future.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.blopeur.com" # the base hostname & protocol for your site, e.g. http://example.com
author:
  twitter: blopeur



# Company Information
company_name: Blopeur Ltd.
address_line: 91-97 Ormeau Road, Belfast, Northern Ireland, BT7 1SH
telephone_number: +44 (0) 7534678673
fax_number: +44 (0) 7534678673
company_email: info@blopeur.com
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2311.917726046637!2d-5.926561784114372!3d54.58782378025785!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x486108fc866f7f1d%3A0xb1b6531e6806646a!2sOrmeau%20House%2C%2091-97%20Ormeau%20Rd%2C%20Belfast%20BT7%201SH!5e0!3m2!1sen!2suk!4v1575656336802!5m2!1sen!2suk

# Social Link

twitter_link: https://twitter.com/blopeur
linkedin_link: https://www.linkedin.com/company/blopeur-limited


#seo
twitter:
  username: blopeur
  card: summary

logo: "https://www.blopeur.com/assets/ico/favicon.ico"

social:
  name: Benoit Hudzia
  links:
    - https://twitter.com/blopeur
    - https://www.linkedin.com/in/BenoitHudzia
    - https://www.linkedin.com/company/blopeur-limited
    - https://www.reflectionsofthevoid.com/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
